// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC83IFzQhMn_h2_iQeqTNCXNEqf6jva3gI',
    appId: '1:602151242105:web:1110b5f6e64418a2d887a8',
    messagingSenderId: '602151242105',
    projectId: 'gotogym-40538',
    authDomain: 'gotogym-40538.firebaseapp.com',
    storageBucket: 'gotogym-40538.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCGMmHRY_wzF6jy9I8BK_Ai8Ssk4F6C5s',
    appId: '1:602151242105:android:b0eafcef3da5ad27d887a8',
    messagingSenderId: '602151242105',
    projectId: 'gotogym-40538',
    storageBucket: 'gotogym-40538.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn9SkDqT7BkJnIGpudwXxQBaLzO5KwrPU',
    appId: '1:602151242105:ios:bd6b66230697e85bd887a8',
    messagingSenderId: '602151242105',
    projectId: 'gotogym-40538',
    storageBucket: 'gotogym-40538.firebasestorage.app',
    iosBundleId: 'com.example.gotogym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn9SkDqT7BkJnIGpudwXxQBaLzO5KwrPU',
    appId: '1:602151242105:ios:bd6b66230697e85bd887a8',
    messagingSenderId: '602151242105',
    projectId: 'gotogym-40538',
    storageBucket: 'gotogym-40538.firebasestorage.app',
    iosBundleId: 'com.example.gotogym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC83IFzQhMn_h2_iQeqTNCXNEqf6jva3gI',
    appId: '1:602151242105:web:81cb04328d9f3314d887a8',
    messagingSenderId: '602151242105',
    projectId: 'gotogym-40538',
    authDomain: 'gotogym-40538.firebaseapp.com',
    storageBucket: 'gotogym-40538.firebasestorage.app',
  );
}
